apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend-deployment
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
        - image: ghcr.io/mrchristmas96/simple-fortune-cookie/simple-fortune-cookie-frontend:latest
          name: simple-fortune-cookie-frontend
          env:
            - name: BACKEND_PORT
              value: "9000"
            - name: BACKEND_DNS
              value: backend-service
