name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.0
      - name: Install dependencies
        run: go mod download
      - name: Run test
        run: go test backend/main_test.go && go test frontend/main_test.go

