name: Cookies :)
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
  build:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Build 
        run: go build -v ./frontend && go build -v ./backend
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run test
        run: go test ./backend/main_test.go && go test ./frontend/main_test.go

