name: Cookies :)
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: .

  build:
    runs-on: ubuntu-latest
    needs: [init]
    steps:
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: . 
      - name: init
        run: go mod init frontend && go mod init backend
      - name: Build 
        run: go build -v frontend && go build -v backend
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Run test
        run: go test backend/main_test.go && go test frontend/main_test.go

