
on: push
jobs:
  Build:
    name: Main ci workflow
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3       
      - name: Build application
        run: go build -o backend && go build -o frontend
      - name: Test
        run: go test backend/my_test.go && go test frontend/my_test.go
      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
      - name: Upload Jar
        uses: actions/upload-artifact@v3
        with: 
          name: jar
          path: app/build/libs/app-0.1-all.jar
